### ISSUE TITLE
Defining Commands

### ISSUE THREAD

**Issue by Ionic-Wolf** [Virodroid/easyTello#14]
I was wanting to do a flip, but as far as I can get it is mydrone.flip(direc = ~~). I have tried putting forward, backwards, left, and right where the ~~ is, and I haven't been successful. If it is possible to define all commands for mydrone.{command} in the ReadMe.md would be helpful.

**Comment by ezrafielding** [comment]
The flip command in easyTello accepts the same commands as the ones outlined in the Tello 1.3.0.0 SDK. So to flip forward for instance, you would say `mydrone.flip('f')`. The flip method accepts a single string which defines direction. They are 'l' for left, 'r' for right, 'f' for forward, and 'b' for backward. I do agree that we need a full list of commands in the easyTello docs, but in the mean time, the Tello 1.3.0.0 SDK notes are a good starting point.
